export type UiErrorCode =
  | "HOME_DOMAIN_FEATURES_MATCH_ICONS_VALIDATION"
  | "HOME_DOMAIN_HOW_IT_WORKS_MATCH_ICONS_VALIDATION"
  | "HOME_DOMAIN_PRICING_MATCH_CONFIG_VALIDATION"
  | "HOME_DOMAIN_TESTIMONIALS_MATCH_CONFIG_VALIDATION"
  | "FETCH_GET_ALL_DOMAIN_METRIC_OR_THROW_FAILED";
