export type UserErrorCode =
  | "USER_NOT_FOUND_GET_USER_BY_EMAIL"
  | "GET_USER_BY_EMAIL_FAILED"
  | "USER_NOT_FOUND_CREATE_USER"
  | "CREATE_USER_FAILED"
  | "USER_NOT_FOUND_GET_USER_BY_ACCOUNT"
  | "GET_USER_BY_ACCOUNT_FAILED";
