export type TenantErrorCode =
  | "TENANT_NOT_FOUND_GET_USER_BY_EMAIL"
  | "TENANT_NOT_FOUND_CREATE_USER"
  | "TENANT_NOT_FOUND_GET_USER_BY_ACCOUNT"
  | "TENANT_NOT_FOUND_LINK_ACCOUNT"
  | "TENANT_NOT_FOUND_CREATE_SESSION";
